//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Despacho
    {
        public Despacho()
        {
            this.Acarreo = new HashSet<Acarreo>();
            this.Deposito = new HashSet<Deposito>();
            this.Despachante = new HashSet<Despachante>();
            this.Factura_Despacho = new HashSet<Factura_Despacho>();
        }
    
        public int Id { get; set; }
        public decimal Costo_despacho_producto { get; set; }
        public string Dc { get; set; }
        public System.DateTime Oficializacion { get; set; }
        public decimal Fob_Total { get; set; }
        public decimal Flete_Total { get; set; }
        public decimal Seguro_Total { get; set; }
        public decimal Cotizacion { get; set; }
        public string Codigo_Afip { get; set; }
        public decimal Arancel_Sim { get; set; }
        public decimal Servicio_Guarda { get; set; }
    
        public virtual ICollection<Acarreo> Acarreo { get; set; }
        public virtual ICollection<Deposito> Deposito { get; set; }
        public virtual ICollection<Despachante> Despachante { get; set; }
        public virtual ICollection<Factura_Despacho> Factura_Despacho { get; set; }
    }
}
