//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura_Despacho
    {
        public int Id { get; set; }
        public int DespachoId { get; set; }
        public int Factura_TotalId { get; set; }
    
        public virtual Despacho Despacho { get; set; }
        public virtual Factura_Total Factura_Total { get; set; }
    }
}
