//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConsuPymeDesarrolloEntities : DbContext
    {
        public ConsuPymeDesarrolloEntities()
            : base("name=ConsuPymeDesarrolloEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Acarreo> Acarreo { get; set; }
        public DbSet<Deposito> Deposito { get; set; }
        public DbSet<Despachante> Despachante { get; set; }
        public DbSet<Despacho> Despacho { get; set; }
        public DbSet<Factura_Despacho> Factura_Despacho { get; set; }
        public DbSet<Factura_Total> Factura_Total { get; set; }
        public DbSet<Factura_Total_Producto> Factura_Total_Producto { get; set; }
        public DbSet<Posicion_Arancelaria> Posicion_Arancelaria { get; set; }
        public DbSet<Producto> Producto { get; set; }
        public DbSet<Usuarios> Usuarios { get; set; }
    }
}
