//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posicion_Arancelaria
    {
        public Posicion_Arancelaria()
        {
            this.Producto = new HashSet<Producto>();
        }
    
        public int Id { get; set; }
        public long Numero_Posicion { get; set; }
        public decimal Porcentaje_Iva { get; set; }
        public decimal Porcentaje_Taza_Estadistica { get; set; }
        public decimal Porcentaje_Importacion { get; set; }
    
        public virtual ICollection<Producto> Producto { get; set; }
    }
}
