//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.Factura_Total_Producto = new HashSet<Factura_Total_Producto>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public string Codigo { get; set; }
        public int Posicion_ArancelariaId { get; set; }
    
        public virtual ICollection<Factura_Total_Producto> Factura_Total_Producto { get; set; }
        public virtual Posicion_Arancelaria Posicion_Arancelaria { get; set; }
    }
}
